version: '3.8'

services:
  app:
    image:  quay.io/bahgat_20/clinic:backend
    container_name: my_go_app
    networks:
      - my_network
    volumes:
      - go_data:/go/src/app  
    working_dir: /app
    command: go run main.go 

  database:
    image:  quay.io/bahgat_20/clinic:databaseimage
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: bahgat
      MYSQL_DATABASE: clinic
    networks:
      - my_network
    volumes:
      - db_data:/var/lib/mysql

networks:
  my_network:
    driver: bridge

volumes:
  go_data:
    driver: local
  db_data:
    driver: local
