apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: placeholder-image
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URL
          value: mongodb://database:27017/todos
