apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-deployment
  labels:
    app: your-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
      - name: your-container
        image: nginx:latest # Placeholder image, to be updated by the pipeline
        ports:
        - containerPort: 8080
